const fakeData = {
    "login": "MaurooRen",
    "id": 2223743,
    "node_id": "MDQ6VXNlcjIyMjM3NDM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2223743?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MaurooRen",
    "html_url": "https://github.com/MaurooRen",
    "followers_url": "https://api.github.com/users/MaurooRen/followers",
    "following_url": "https://api.github.com/users/MaurooRen/following{/other_user}",
    "gists_url": "https://api.github.com/users/MaurooRen/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MaurooRen/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MaurooRen/subscriptions",
    "organizations_url": "https://api.github.com/users/MaurooRen/orgs",
    "repos_url": "https://api.github.com/users/MaurooRen/repos",
    "events_url": "https://api.github.com/users/MaurooRen/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MaurooRen/received_events",
    "type": "User",
    "site_admin": false,
    "name": "MaurooRen",
    "company": null,
    "blog": "https://maurooren.com",
    "location": "United States",
    "email": null,
    "hireable": null,
    "bio": "Learning + Technology = Ideas that change the world",
    "twitter_username": null,
    "public_repos": 47,
    "public_gists": 0,
    "followers": 3,
    "following": 1,
    "created_at": "2012-08-26T21:40:22Z",
    "updated_at": "2021-01-26T22:42:41Z"
  }

export default fakeData